name: "gemspot_onnx"
platform: "onnxruntime_onnx"
max_batch_size: 128

input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 25 ]
  }
]

output [
  {
    name: "label"
    data_type: TYPE_INT64
    dims: [ 1 ]
  },
  {
    name: "probabilities"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]

dynamic_batching {
  preferred_batch_size: [ 8, 16, 32 ]
  max_queue_delay_microseconds: 2000
}

instance_group [
  {
    kind: KIND_CPU
    count: 1
  }
]
